name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      working-directory: ./web/demo-app
      run: mvn clean package

    #- name: Log in to Amazon ECR
    #  run: |
    #    aws ecr get-login-password --region tu-region | docker login --username AWS --password-stdin <tu-registro>

    - name: Build, tag, and push Docker image
      working-directory: ./web
      run: |
        pwd
        ls -l
        docker build -t my-springboot-app -f Dockerfile.prod .
        docker tag my-springboot-app:latest athesto/my-springboot-app:latest
        docker push athesto/my-springboot-app:latest

