name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    #- name: Log in to Amazon ECR
    #  run: |
    #    aws ecr get-login-password --region tu-region | docker login --username AWS --password-stdin <tu-registro>

    #- name: Build, tag, and push Docker image
    #  run: |
    #    docker build -t my-springboot-app .
    #    docker tag my-springboot-app:latest <tu-registro>/<tu-repositorio>:latest
    #    docker push <tu-registro>/<tu-repositorio>:latest

