
FROM openjdk:17
RUN microdnf update
RUN microdnf install -y unzip zip
RUN curl -s "https://get.sdkman.io" | bash && \
    source "$HOME/.sdkman/bin/sdkman-init.sh" && \
    sdk install springboot

#ADD . /app
#WORKDIR /app
#RUN mvn clean package
#CMD ["java", "-jar", "/app/target/dockerfile-spring-boot-0.0.1-SNAPSHOT.jar"]

